### ISSUE TITLE
better test server? use jenkins?

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#738] opened 2014-03-07 11:27 UTC

**Comment by eugenk** [comment] 2015-01-16 14:31
The docker instance is running on http://john.iws.cs.ovgu.de:49153

One build needs about 5:30 minutes to pass. This is way faster than on travis. 

What still needs to be done:
* [ ] periodically build staging (once a day)
* [ ] notify developers when staging is red
* [ ] run the docker container on system startup on john.iws.cs.ovgu.de with the command `docker run -d -P -v /home/ontohub/ontohub-ci-data:/data ontohub-ci`

**Comment by jelmd** [comment] 2015-01-20 07:19
Well, docker is IMHO not the right thing to use here: it targets "stateless" application and thus is usually interesting (with some minor exceptions) for big DCs only, e.g. running 10^r (with r>1) isolated web server instances for several customers (like Strato, 1&1, etc.). As soon as one needs "infrastructure", i.e. other running services like cron, log/fs maintenance, a firewall, or possibly backups, etc. using docker becomes a hurdle/requires writing more or less sophisticated hooks/leads to re-inventing the wheel (which often results in a much worse quality as existing solutions). So docker is rarely useful for developers and normal companies - they need a more flexible, "full blown container" for efficient work/testing => pure lxc zones.

So my suggestion is to put a new minimal zone (jenkins.ontohub.org or whatever?) on the ontohub server (OHS) where you can install it and thus get the remaining tasks resolved automagically ;-)

The only things to be obeyed are to write the commands used to set it up into a script and to store beneath /data/ all valuable data, which need to be put on the backups!

The main reasons for this are: We use such scripts together with  those in https://github.com/ontohub/admin-scripts/tree/puma/scripts/install/ (our "docker framework" if you want) to be able to reproduce/clone/restore any zone on any machine with the same OS in the GZ. The separation of reproducible and not-easy-to-reproduce data is important as well, because we do not need the backups of 100+ whole OS installations or other SW, which can be obtained/installed easily via package manager or repo fetch+build[+install]. It costs a lot of time to backup such useless data, consumes a lot of BW and CPU power (most backup SW still operates like 20 years ago and thus is not green at all)...

**Comment by tillmo** [comment] 2015-01-20 11:09
Now that @eugenk has used docker, it should be possible to run the docker container on system startup

**Comment by eugenk** [comment] 2015-01-20 11:23
In this Docker instance, the state/data to backup is separated from the docker container. It's in a docker volume which is located at `~ontohub/ontohub-ci-data/` on john. This is the only data that needs to be backed up once in a while (except for the cloned ontohub repositories in there). When started with the right parameters, the docker container actually loads this state. 

I understand that docker is not the best technology for such a task, but lxc is not as well documented and comparing the scripts you have for setting up the ontohub container, the slim 88 lines (+119 lines of the scripts) of the current Dockerfile seem rather easy to oversee/maintain.

**Comment by jelmd** [comment] 2015-01-21 15:10
As said, for now, docker should not be used for such scenarios and there is no backup for lab machines. john is a lab machine. It can be turned off any time by anyone, which already happend several times last year! Also on the new year break the labs are locked down for 1-2 weeks powerwise! So if availability doesn't matter, go ahead, but than give a hint, because it is planed, that john gets recycled ASAP (it is a bloated ad hoc installation - no one wants to maintain it ...).

**Comment by tillmo** [comment] 2015-01-21 16:04
john also hosts the WADT website. This must be available permanenty, also during breaks.

**Comment by jelmd** [comment] 2015-01-21 16:07
Yepp, should be hosted on the OHS as well.

**Comment by eugenk** [comment] 2016-01-04 11:16
Todo: notify developers when staging is red (and tick the check box in https://github.com/ontohub/ontohub/issues/738#issuecomment-70260999)

**Comment by eugenk** [comment] 2016-01-08 09:11
@jelmd: Are there SMTP credentials that we can use for sending mails from jenkins to the developer mailing list? (only when staging tests fail)

Or shall I register an independent mail account (e.g. gmail) just for this purpose?

**Comment by jelmd** [comment] 2016-01-08 17:27
Ehmm, what?

BTW (because I read 'john' above): Just incase you have still something valueable on john: the HDD is dieing (that's why it took me some time to get it up after x-mas break) - next time it makes trouble or in the next semester break it gets flattened! (wadt2014 has already been moved away - is now static on theo's main httpd).

**Comment by eugenk** [comment] 2016-01-08 17:32
Ah, good to know. We have our continuous integration/testing environment on john. It's not this valuable because it's just a running docker instance that we can recreate easily. (BTW: We know docker is not the best choice, but it was easy to set up.)

About SMTP: Every time a nightly test of the staging branch fails on this CI system, we want to send an email to the developer mailing list. Therefore, we need an SMTP account.

**Comment by jelmd** [comment] 2016-01-12 20:36
If you use our local mail gateways (mail.iws.cs...) or the systems default mail submission program like sendmail etc., no account is needed.

**Comment by eugenk** [comment] 2016-01-18 10:13
Thanks, but I'm still having trouble configuring the mail issue. The following screenshots show the configuration options in our CI service. I can't find a working config. Could you tell us one (via email if this shouldn't be public), please?

----

<img width="1154" alt="screen shot 2016-01-18 at 11 06 58" src="https://cloud.githubusercontent.com/assets/339751/12388570/f5708352-bdd3-11e5-9372-8a1067a2054f.png">

----

<img width="1152" alt="screen shot 2016-01-18 at 11 07 16" src="https://cloud.githubusercontent.com/assets/339751/12388571/f5710dea-bdd3-11e5-82a1-2522ff90d9a8.png">

----

<img width="1153" alt="screen shot 2016-01-18 at 11 07 47" src="https://cloud.githubusercontent.com/assets/339751/12388572/f574eee2-bdd3-11e5-9bb5-9a45c89c80f9.png">

**Comment by jelmd** [comment] 2016-01-19 21:29
As said (and chomped by github somewhere, grrr, and thus again): there are different ways to send mail from a Unix \[like\] (*x) machine. One is to talk directly SMTP with a mail gateway aka mail delivery daemon|service, or, the default on *x driven boxes, is to use a message (mail) submission program (msp) like sendmail [under the hood] to send a mail, which in turn uses usually the system's settings to talk SMTP to an appropriate mail gateway to deliver it. Last but not least on many *x boxes there is also a mail submission agent (MSA) running, which listens for new messages per default on the localhost bound interface port 25 (and sometimes even on 587 - IMHO for obscure/obsolete reasons, i.e. an ancient construct from the previous millennium), which often behaves like a "dumb" mail gateway, i.e. one needs to talk SMTP with it and it just forwards the stuff to a more sophisticated MTA.

Usually all modern mail gateways (MTAs) listen on port 25 and support StartTLS. Not sure, what 'SSL' in the images above indicates, but normally it means the whole connection gets established/protected using SSL and therefore port 25 is NOT the right port to use it. So whether an MTA supports this kind of SSL and if so on which port, solely depends on its settings (IIRC there is no RFC/Standard for this).

Our mail gateways follow standards and thus use port 25, support StartTLS (but not the port 587 non-sense) and their FQDN is mail.${domain}. Our UNIX lab boxes as well as servers have usually an MSA (sendmail) running, which listens on localhost:25 (sometimes on 587 for backward compat as well - but don't count on it), which does not support StartTLS/SSL for incoming messages - it is just a "dumb" daemon, which forwards everything to the central mail gateway, which in turn does the real work. As said, network local (intranet) clients aka MUAs/MSAs/MTAs don't need to authenticate for relaying mails, but external (internet) clients are required to authenticate, if they want the MTA to relay their mails to non-local recipients.

So, there are a lot of things (loT ;-)) which can go wrong and thus we should use a systematic approach to troubleshoot the problem: Therefore I need an answer wrt. the following questions first: What is the app actually doing (talks directly SMTP to an MTA/MSA OR uses what msp)? Who is the recipients of the intended mail? On which machine (IP) does it run? What error messages do you get? Are there any logs related to this problem?

I have no clue, what 'Default user e-mail suffix' means - IIRC such a term does not exist in SMTP related RFCs. So ...

**Comment by eugenk** [comment] 2016-01-26 13:49
> Therefore I need an answer wrt. the following questions first: What is the app actually doing (talks directly SMTP to an MTA/MSA OR uses what msp)?

It should talk directly SMTP. It uses [JavaMail](https://javamail.java.net/nonav/docs/api/overview-summary.html#overview_description) to send mails via SMTP.

> Who is the recipients of the intended mail?

Our developer mailing list

> On which machine (IP) does it run?

a docker instance on john.iws.cs.ovgu.de, exposing TCP port 49153 (mapped to docker-instance-internal port 8080) for HTTP, running as user `ontohub`.

> What error messages do you get? Are there any logs related to this problem?

After configuring this:
* System Admin e-mail address: `jenkins@john.iws.cs.ovgu.de` (used as sender address)
* SMTP server: `mail.iws.cs.ovgu.de`
* `[ ]` Use SMTP Authentication (not checked)
* Charset: `UTF-8`

(leaving everything else empty) and trying to send a test mail to my personal address, I get:
```
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 554 5.7.1 Protocol violation

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1835)
        [Java stacktrace]
```

Maybe there is a problem caused by using docker and not opening/mapping ports? Or a firewall issue? When there is no "System Admin e-mail address" configured, jenkins uses `nobody@nowhere` as a default and then we get
```
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 553 5.1.8 <recepient_email_address@example.com>... Domain of sender address nobody@nowhere does not exist
```

**Comment by jelmd** [comment] 2016-01-26 16:29
Oh, as said, john is dead meat and gets flattened next month. Therefore we do not waste any time for it!

**Comment by eugenk** [comment] 2016-01-27 12:37
Is there another machine that we can run our CI suite on?

**Comment by jelmd** [comment] 2016-01-28 04:31
Yepp, in theory as many as you want :)
You just need to say, which software/profile you need, and I'll set it up.

**Comment by eugenk** [comment] 2016-01-28 08:20
Basically we need an Ontohub developer instance with jenkins installed and running. The setup is described in the Dockerfile (and accompanying scripts) at https://github.com/ontohub/ontohub-ci. I wanted to put this into a script to set up an LXC container, but I haven't had time to get to know LXC yet.

**Comment by eugenk** [comment] 2016-08-02 10:46
Closing in favour of #1757.

**Closed by eugenk** 2016-08-02 10:46 UTC
Labels: in progress
