### ISSUE TITLE
ontologies are not analysed

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#1514] opened 2015-10-27 14:25 UTC
as mentioned already in #1479, Ontohub no longer analyses ontologies. The status remains "pending" indefinitely, for all new or changed ontologies. This means that Ontohub's most basic functionality is not available.

**Comment by SGraef** [comment] 2015-10-29 10:44
right now we have the problem that we can't deploy on ontohub.org and we didn't find out the what the problem is

**Comment by tillmo** [comment] 2015-10-29 11:23
what is the message that you get? (I thought that this happens on develop.ontohub.org, and I am still waiting for a capistrano configuration that I could show to Jens.)

**Comment by eugenk** [comment] 2015-10-29 12:30
No, there was a misunderstanding. The deployment passed eventually.

**Comment by tillmo** [comment] 2015-10-29 12:34
deployment on which machine(s) passed?

**Comment by eugenk** [comment] 2015-10-29 12:35
Now it passed on all machines. I solved the merge conflicts on ontohub.org and develop.ontohub.org

**Comment by tillmo** [comment] 2015-11-03 10:41
I have the impression that the situation is unchanged: sidekiq does not process any jobs, although there are lots of enqueued and scheduled jobs. Any progress with this issue?

**Comment by SGraef** [comment] 2015-11-03 10:45
The problem is that we don't know why the sidekiqprocesses which should do the hets parsing are fast will be quited after start of god like we said yesterday in the meeting

**Comment by tillmo** [comment] 2015-11-06 06:50
could you please install jesus in order to monitor god's behaviour?

**Comment by SGraef** [comment] 2015-11-06 08:54
i don't think this would help beacuse it only serves the god status command via webinterface so we dont get new information of this

**Comment by eugenk** [comment] 2015-11-06 09:00
I'm currently working on #1226. Maybe this will solve the problem.

**Comment by SGraef** [comment] 2015-11-06 09:33
i have maybe an idea it looks like the problem is sidekiq and not god so maybe we should clear the queue and then re arrange the ontologies because the old load balancing mechanism could destroy the wanted behaviour on a strange way, it is just a quess no specific reasons. but i don't think we lose any data so its worth to try

**Comment by tillmo** [comment] 2015-11-06 13:28
yes, please

**Comment by SGraef** [comment] 2015-11-06 13:47
okay now i have done it the processes not dissapear anymore i have started all pending and processing ontologies new

**Comment by tillmo** [comment] 2015-11-07 09:15
currently, only 1 ontology is processing and 155 are pending. There should be more processing ontologies.

**Comment by SGraef** [comment] 2015-11-07 13:16
considering sidekiq we have 20 busy processes

**Comment by SGraef** [comment] 2015-11-07 13:18
i have no idea from where this strange behavior comes from

**Comment by tillmo** [comment] 2015-11-07 14:07
the numbers are the same as five hours ago. It seems that there is no progress at all.

**Comment by tillmo** [comment] 2016-02-01 21:18
it seems to me that this can be closed now

**Comment by eugenk** [comment] 2016-02-01 21:21
Indeed. This is also fixed by #1557. I'm closing this issue.

**Closed by eugenk** 2016-02-01 21:21 UTC
